# Generated by Django 6.0.3 on 2026-05-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymentwebhook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentWebhook',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
