# Generated by Django 6.0.3 on 2026-05-02 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_transaction_sale'),
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='rh.employee', verbose_name='Vendedor/Funcionário'),
        ),
    ]
