# Generated by Django 6.0.3 on 2026-05-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_paymentwebhook_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(help_text='Nome da instância na API do WhatsApp (ex: Evolution API)', max_length=100, unique=True)),
                ('instance_key', models.CharField(blank=True, help_text='Chave de segurança da instância', max_length=255)),
                ('status', models.CharField(default='DISCONNECTED', max_length=50)),
                ('qr_code_base64', models.TextField(blank=True, help_text='Último QR Code gerado para conectar', null=True)),
                ('number', models.CharField(blank=True, help_text='Número de telefone conectado', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_integration', to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_jid', models.CharField(help_text='ID do contato (número@s.whatsapp.net)', max_length=100)),
                ('message_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('is_from_me', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('processed', models.BooleanField(default=False)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappintegration')),
            ],
        ),
    ]
